version: '3.3'
services:
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    network_mode: "host"
    depends_on:
      - prometheus

